### ISSUE TITLE
Eugenics and Statistics

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/StatTalk#2]
Many of us recognize that primary figures in Statistics (Galton, Pearson, Fisher to many a few) held views about eugenics. As a sidenote, I am spending the summer of 2020 learning about connections between eugenics and psychology [see my blog](https://crumplab.github.io/blogposts/7_13_20_PsychEugenics/7_13_20_PsychEugenics.html), and the connections are numerous.

I believe it is necessary that we contextualize our teaching of statistics and psychology in terms of eugenics, for several reasons. I'll find another space to elaborate on the reasons. However, for our department, I think it would be good have some standards around teaching about these issues. For example, we all apparently agree that everyone needs to learn about t-tests and Pearson's R. I think we should all consider integrating perspectives on eugenics and ethics into our teaching.

To take one example, in the past I have referenced that Karl Pearson held eugenic views in my lectures (and I did not write anything about this in our OER textbook, although I'm planning to change that), and that's about it. However, I have since learned more about the scope and pervasiveness of eugenics in general (in society), and also the extremes of Karl Pearson's eugenics. For example, I think it would be important to discuss how Pearson created and then used his correlation co-efficient for the purpose preventing Jewish people from emigrating to UK. For example, this paper is Part I of III papers by Pearson.

Pearson, K., & Moul, M. (1925). The problem of alien immigration into Great Britain, illustrated by an examination of Russian and Polish Jewish children. Annals of Eugenics, 1(1), 5–54. https://doi.org/10/cvn6gq

These papers go on for hundreds of pages, and describe endless measurements of Jewish people, and endless correlations between measures. This is Pearson applying his own statistical tools to "solve the jewish problem". It is heart-wrenching stuff to read. 

My position is that I feel obligated to make sure our students understand this history when we teach statistics. So, I am endeavoring to figure out how to do this. It would be great if people want to share resources on this, and/or commit to incorporating discussions of these issues into our curriculum. 

There is much more to be worked on with respect to this topic, and I'll keep adding to this thread as I think more about it.

**Comment by CrumpLab** [comment]
To do list:

- [ ] Survey faculty who teach statistics to find out how we all currently discuss eugenics in our teaching of statistics
- [ ] Currently in the process of introducing some discussion of eugenics to the OER textbook <https://crumplab.github.io/statistics/>, this work is being done in the beta branch of <https://github.com/CrumpLab/statistics>
- [ ] Personally, I would like to survey all intro stats textbooks to determine how eugenics is (or is not) handled

I think that teaching the history of eugenics in statistics and psychology can be a valuable tool, both for raising awareness about stuctural racism and eugenics in the discipline, but also as potent object lessons for our students about the importance of ethics in scientific inquiry.

**Comment by stephengv** [comment]
Thanks For bringing this up Matt. I'm excited to discuss high-level pedagogical issues with you all, and you picked a doozy to start with! Here are my initial musings. 

I have pondered including more discussion of eugenics and historical/social issues as they connect to statistics in my class over the years, and while I agree that these are important, meaningful, and interesting topics, I've been wary of bringing them up in an introductory statistics class. 

My first concern is that I worry that students mat feel combative towards the _mathematical_ content itself if it's placed in the context of "the guy who developed this literally hated you and developed this math to hurt you".

Secondly, I think if given my druthers I would erase Fisher from history overall, but if his mathematical contributions are too important to forget (a basic premise of this issue, as Matt rightfully pointed out), I have a gut instinct to not give his social ideas any dignity or validity by repeating them. A "focus on the positive" sort of perspective. I understand how this instinct is incompatible with "raising awareness about structural racism and eugenics in the discipline", but I am still trepidacious about breaching the topic. I have an image in my head of a biased, hateful student sitting in my class thinking "Aha! Fisher says Math says that racism is right!" as I try to transmit a completely different message.  

Those concerns aside, I have led discussions on eugenics in my lectures previously, typically at the end of the semester. I make it a part of a larger conversation about the overall historical course of statistics, ending with a discussion on the use of modeling in targeted advertising. I have found those lectures to be somber, but discussion provoking for my students. Overall, they seem quite successful when judging from the students who are vocal and engage in the conversation, but it's the students staying quiet for one reason or another during those lectures that worry me.    

Just to be clear, I am playing a bit of a Devil's advocate here. I'm not raising these issues to argue against an increased historical perspective in 3400 courses, which highlights the role of structural racism. I do however think we need to be wary of how and when we raise these issues.

**Comment by CrumpLab** [comment]
Thanks for being the first to comment here!

I appreciate the devil's advocate perspective here, and totally agree that it would be good to discuss how to go about discussing these issues with our students. I'll also mention that pedagogy around statistics and eugenics is part of a much bigger problem we have in the department that nobody seems to talk about very much, which are the connections between psychology and eugenics (see my disorganized blog). I bring this up because I don't think that silence is the answer (and, I'm not saying you were saying that :) ). I think that broad treatment of eugenics across our entire curriculum is probably very necessary. This kind of broad treatment could alleviate specific difficulties with bringing up the topic seemingly at random in the context of specific courses. 

Anyway, this is a heavy-lifting topic, I'm thinking it will take some extra effort to resolve.

**Comment by CrumpLab** [comment]
Because the online teaching effectiveness course is just starting, I'm going to close this topic for now, and raise it again later.
